# Generated by Django 4.2.6 on 2024-02-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
