# Generated by Django 4.2.6 on 2024-02-02 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_blood_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
