# Generated by Django 4.2.6 on 2024-02-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_city_id_alter_district_id_alter_donor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_district', to='api.district'),
        ),
    ]
