# Generated by Django 4.2.6 on 2024-02-17 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_alter_city_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolelink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
