# Generated by Django 4.2.6 on 2024-01-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0002_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
